
person:
  name: qj
  age: 3
  happy: true
  birth: 2021/11/01
  maps: {k1: v1, k2: v2}
  lists:
    - code
    - girl
  dog:
    name: wangcai11
    age: 3

server:
  port: 8080
spring:
  profiles:
    active: prod
---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: prod